<?php
session_start();
include 'db.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    die("Access Denied.");
}

// 1. Get filter parameter
$filter = isset($_GET['filter']) ? $_GET['filter'] : '30days';
$where_clause = "";
$report_title = "All Time Revenue Record";

if ($filter === '30days') {
    $where_clause = "WHERE b.created_at >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)";
    $report_title = "Last 30 Days Revenue Record";
}

// 2. Fetch total stats dynamically based on filter
$stat_query = $conn->query("SELECT SUM(total_price) as grand_total, COUNT(id) as total_orders FROM bookings b $where_clause");
$stats = $stat_query->fetch_assoc();
$grand_total = $stats['grand_total'] ? $stats['grand_total'] : 0;
$total_orders = $stats['total_orders'] ? $stats['total_orders'] : 0;

// 3. Fetch all filtered bookings
$query = "
    SELECT b.id, u.fullname, u.phone, b.booking_date, b.created_at, b.total_price 
    FROM bookings b 
    JOIN users u ON b.user_id = u.id 
    $where_clause 
    ORDER BY b.created_at DESC
";
$result = $conn->query($query);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Financial Report - Splash Mania</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #e9ecef; color: #212529; font-family: 'Inter', 'Segoe UI', sans-serif; }
        .a4-page { width: 210mm; min-height: 297mm; background: white; margin: 20mm auto; padding: 20mm; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
        .report-header { border-bottom: 2px solid #198754; padding-bottom: 20px; margin-bottom: 30px; }
        .table th { background-color: #198754 !important; color: white !important; font-size: 0.9rem; text-transform: uppercase; }
        .table td { font-size: 0.95rem; vertical-align: middle; }
        
        /* ---------- PRINT SPECIFIC STYLES ---------- */
        @media print {
            @page { margin: 0; }
            body { background: white; margin: 1cm; padding: 0; }
            .a4-page { margin: 0; box-shadow: none; width: 100%; padding: 0; }
            .no-print { display: none !important; }
            .table th { background-color: #198754 !important; color: white !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            .bg-light { background-color: #f8f9fa !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
    </style>
</head>
<body>
    <div class="text-center my-5 no-print">
        <button onclick="window.print()" class="btn btn-lg btn-success rounded-pill shadow px-5 fw-bold transition-all hover-lift">
            <i class="fa-solid fa-print me-2"></i> Save as PDF / Print
        </button>
        <p class="text-muted mt-3 small"><i class="fa-solid fa-circle-info me-1"></i> Tip: Select <strong>"Save as PDF"</strong> in the browser print dialog destination.</p>
    </div>

    <div class="a4-page">
        <div class="report-header d-flex justify-content-between align-items-end">
            <div>
                <h1 class="fw-bold text-success mb-1" style="letter-spacing: -1px;">SPLASH MANIA</h1>
                <h4 class="text-muted mb-0"><?= $report_title ?></h4>
            </div>
            <div class="text-end text-muted small">
                <p class="mb-0"><strong>Generated On:</strong> <?= date('d M Y, h:i A') ?></p>
                <p class="mb-0"><strong>Generated By:</strong> Administrator</p>
            </div>
        </div>

        <div class="row mb-4">
            <div class="col-6">
                <div class="p-3 bg-light border rounded">
                    <p class="mb-1 text-muted fw-bold text-uppercase small">Total Ticket Volume</p>
                    <h3 class="fw-bold mb-0"><?= $total_orders ?> Orders</h3>
                </div>
            </div>
            <div class="col-6">
                <div class="p-3 bg-light border rounded text-end">
                    <p class="mb-1 text-muted fw-bold text-uppercase small">Grand Total Revenue</p>
                    <h3 class="fw-bold text-success mb-0">RM <?= number_format($grand_total, 2) ?></h3>
                </div>
            </div>
        </div>

        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Ref ID</th>
                    <th>Customer Name</th>
                    <th>Travel Date</th>
                    <th>Transaction Time</th>
                    <th class="text-end">Paid (RM)</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($result && $result->num_rows > 0): ?>
                    <?php while ($row = $result->fetch_assoc()): ?>
                        <tr>
                            <td><strong>#SM-<?= str_pad($row['id'], 4, '0', STR_PAD_LEFT) ?></strong></td>
                            <td><?= htmlspecialchars($row['fullname']) ?></td>
                            <td><?= date("d M Y", strtotime($row['booking_date'])) ?></td>
                            <td class="text-muted"><?= date("d M Y, H:i", strtotime($row['created_at'])) ?></td>
                            <td class="text-end fw-bold text-dark">RM <?= number_format($row['total_price'], 2) ?></td>
                        </tr>
                    <?php endwhile; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5" class="text-center py-5 text-muted">No records found for the selected time period.</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>

        <div class="mt-5 pt-5 row">
            <div class="col-4 text-center">
                <hr style="border-top: 1px solid #333; margin-bottom: 5px;">
                <p class="fw-bold small text-muted text-uppercase">Prepared By</p>
            </div>
            <div class="col-4"></div>
            <div class="col-4 text-center">
                <hr style="border-top: 1px solid #333; margin-bottom: 5px;">
                <p class="fw-bold small text-muted text-uppercase">Authorized Signature</p>
            </div>
        </div>
    </div>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</body>
</html>